# version: '3.8'
services:
  # Laravel Application
  blog:
    build:
      context: ../laravel
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - ../laravel:/var/www/html
    environment:
      - APP_ENV=production
      - DB_HOST=mysql
      - REDIS_HOST=redis
      - QUEUE_CONNECTION=redis
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  # FastAPI Application
  api:
    build:
      context: ../fastapi
      dockerfile: Dockerfile
    container_name: fastapi-app
    restart: unless-stopped
    volumes:
      - ../fastapi:/app
    environment:
      - ENVIRONMENT=production
    networks:
      - app-network

  # Node.js Application
  app:
    # build:
    #   context: ../nodejs
    #   dockerfile: Dockerfile
    image: ghcr.io/codedsultan/xurl:latest
    container_name: nodejs-app
    restart: unless-stopped
    volumes:
      - /var/www/apps/nodejs:/app
      # - app_db_data_sqlite:/var/lib/kutt
      # - custom:/kutt/custom
      - /var/www/apps/nodejs/db_data_sqlite:/var/lib/kutt  # Store the SQLite database inside nodejs folder
      - /var/www/apps/nodejs/custom:/kutt/custom 
    env_file:
      - /var/www/apps/nodejs/.env
    environment:
      DB_FILENAME: "/var/lib/kutt/data.sqlite"
    networks:
      - app-network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../laravel:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      # - blog
      # - api
      - app
    networks:
      - app-network

  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    networks:
      - app-network

  # Redis Service
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./redis/data:/data
    networks:
      - app-network

  # Laravel Queue Worker
  laravel-queue:
    build:
      context: ../laravel
      dockerfile: Dockerfile
    container_name: laravel-queue
    restart: unless-stopped
    command: php artisan queue:work
    depends_on:
      - blog
      - redis
    volumes:
      - ../laravel:/var/www/html
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # Remove the certonly command to run interactively
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network
    restart: unless-stopped
networks:
  app-network:
    driver: bridge

# volumes:
#   mysql_data:
#   redis_data:
#   certbot_conf:
#   certbot_www:
  # app_db_data_sqlite:
  # custom: