global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cAdvisor:8080']

  - job_name: 'docker_containers'
    static_configs:
      - targets: ['<host-ip>:9323']
      # ['host.docker.internal:9323']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['<host-ip>:9100']  # Replace <host-ip> with your host machine's IP address or use 'localhost'

