global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker_containers'
    static_configs:
      - targets: ['host.docker.internal:9323']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
