name: Deploy Nginx

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add GitHub to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Configure git to use merge
        run: git config --global pull.rebase false

      - name: Change permissions for SSL directory
        run: |
          sudo chmod -R 777 ${{ secrets.DEPLOY_PATH }}/ssl || true
          sudo chown -R $(whoami) ${{ secrets.DEPLOY_PATH }}/ssl || true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}
          
      - name: Deploy Nginx
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |

          ssh -o StrictHostKeyChecking=no "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}" << 'ENDSSH'
            set -e  # Exit on error
            cd "${{ secrets.DEPLOY_PATH }}"
            docker-compose stop app nginx && docker-compose rm -f app nginx
            GIT_SSH_COMMAND='ssh -i /home/deploy/.ssh/nodejs_deploy_key' git pull origin main -f
            echo ${{ secrets.PAT_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker-compose pull app nginx
            docker-compose up -d app nginx
          ENDSSH
